version: 2

before:
  hooks:
    - go mod tidy

# Disable binary builds - Docker only for now
# CGO cross-compilation for SQLite is complex and requires platform-specific toolchains
# Users can build from source if they need native binaries
builds:
  - skip: true

# No archives needed for Docker-only release
archives:
  - id: skip-archives

# Skip checksums since we're not distributing binaries
checksum:
  disable: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

dockers:
  - image_templates:
      - "karloscodes/formlander:{{ .Version }}-amd64"
      - "karloscodes/formlander:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "karloscodes/formlander:{{ .Version }}-arm64"
      - "karloscodes/formlander:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "karloscodes/formlander:{{ .Version }}"
    image_templates:
      - "karloscodes/formlander:{{ .Version }}-amd64"
      - "karloscodes/formlander:{{ .Version }}-arm64"
  
  - name_template: "karloscodes/formlander:v{{ .Major }}"
    image_templates:
      - "karloscodes/formlander:{{ .Version }}-amd64"
      - "karloscodes/formlander:{{ .Version }}-arm64"
  
  - name_template: "karloscodes/formlander:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "karloscodes/formlander:{{ .Version }}-amd64"
      - "karloscodes/formlander:{{ .Version }}-arm64"
  
  - name_template: "karloscodes/formlander:latest"
    image_templates:
      - "karloscodes/formlander:latest-amd64"
      - "karloscodes/formlander:latest-arm64"

release:
  github:
    owner: karloscodes
    name: formlander
  prerelease: auto
  mode: replace
  header: |
    ## Formlander {{ .Tag }}
    
    Self-hosted form backend with SQLite storage.
    
    ### Quick Start with Docker
    
    ```bash
    docker run -d \
      -p 8080:8080 \
      -e FORMLANDER_SESSION_SECRET=$(openssl rand -hex 32) \
      -e FORMLANDER_ANON_SALT=$(openssl rand -hex 32) \
      -v $(pwd)/storage:/app/storage \
      karloscodes/formlander:{{ .Version }}
    ```
    
    Then visit `http://localhost:8080` with default credentials:
    - Email: `admin@formlander.local`
    - Password: `formlander`
    
    ### Building from Source
    
    ```bash
    git clone https://github.com/karloscodes/formlander.git
    cd formlander
    git checkout {{ .Tag }}
    make build
    export FORMLANDER_SESSION_SECRET=$(openssl rand -hex 32)
    export FORMLANDER_ANON_SALT=$(openssl rand -hex 32)
    ./bin/formlander
    ```
  footer: |
    ---
    
    **Documentation**: https://formlander.com/docs
    **Full Changelog**: https://github.com/karloscodes/formlander/compare/{{ .PreviousTag }}...{{ .Tag }}
